// examples/app2/frontend/src/App.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { api } from './api'
import type { Board, CurrentUser, Task, TaskColumn } from './types'

const user = ref<CurrentUser | null>(null)
const loading = ref(true)
const errorMsg = ref<string | null>(null)

const boards = ref<Board[]>([])
const selectedBoardId = ref<string | null>(null)
const tasks = ref<Task[]>([])

const newTaskInput = ref<Record<TaskColumn, string>>({ todo: '', doing: '', done: '' })

const COLUMNS: { id: TaskColumn; label: string; color: string }[] = [
  { id: 'todo',  label: 'To Do', color: 'bg-slate-100 text-slate-700' },
  { id: 'doing', label: 'Doing', color: 'bg-amber-100 text-amber-800' },
  { id: 'done',  label: 'Done',  color: 'bg-emerald-100 text-emerald-800' },
]

const displayName = computed(() => user.value?.display_name ?? user.value?.sub ?? '')

onMounted(async () => {
  const params = new URLSearchParams(window.location.search)
  const e = params.get('error')
  const loggedOut = params.get('logout')
  if (e) {
    errorMsg.value = e
    window.history.replaceState({}, '', '/')
  }
  if (loggedOut) {
    window.history.replaceState({}, '', '/')
    loading.value = false
    return
  }
  try {
    const r = await fetch('/api/me')
    if (r.ok) {
      user.value = (await r.json()) as CurrentUser
      loading.value = false
      await loadBoards()
      return
    }
    if (e) {
      loading.value = false
      return
    }
    window.location.href = '/login'
  } catch {
    loading.value = false
  }
})

async function loadBoards(): Promise<void> {
  const list = await api.listBoards()
  boards.value = list
  if (list.length > 0 && !selectedBoardId.value) {
    selectedBoardId.value = list[0]._id
  }
}

watch(selectedBoardId, async (id) => {
  if (!id) {
    tasks.value = []
    return
  }
  tasks.value = await api.listTasks(id)
})

function columnTasks(col: TaskColumn): Task[] {
  return tasks.value.filter(t => t.column === col).sort((a, b) => a.position - b.position)
}

async function addBoard(): Promise<void> {
  const title = window.prompt('새 보드 이름')?.trim()
  if (!title) return
  const created = await api.createBoard(title)
  boards.value = [created, ...boards.value]
  selectedBoardId.value = created._id
}

async function renameBoard(b: Board): Promise<void> {
  const title = window.prompt('보드 이름 변경', b.title)?.trim()
  if (!title || title === b.title) return
  const updated = await api.renameBoard(b._id, title)
  boards.value = boards.value.map(x => (x._id === b._id ? updated : x))
}

async function deleteBoard(b: Board): Promise<void> {
  if (!window.confirm(`"${b.title}" 와 안의 작업을 모두 삭제할까요?`)) return
  await api.deleteBoard(b._id)
  boards.value = boards.value.filter(x => x._id !== b._id)
  if (selectedBoardId.value === b._id) {
    selectedBoardId.value = boards.value[0]?._id ?? null
  }
}

async function addTask(column: TaskColumn): Promise<void> {
  const title = newTaskInput.value[column].trim()
  if (!title || !selectedBoardId.value) return
  const created = await api.createTask(selectedBoardId.value, title, column)
  tasks.value = [...tasks.value, created]
  newTaskInput.value[column] = ''
}

async function moveTask(t: Task, dir: -1 | 1): Promise<void> {
  const order: TaskColumn[] = ['todo', 'doing', 'done']
  const idx = order.indexOf(t.column)
  const next = order[idx + dir]
  if (!next) return
  const updated = await api.updateTask(t._id, { column: next })
  tasks.value = tasks.value.map(x => (x._id === t._id ? updated : x))
}

async function deleteTask(t: Task): Promise<void> {
  await api.deleteTask(t._id)
  tasks.value = tasks.value.filter(x => x._id !== t._id)
}

async function logout(): Promise<void> {
  await api.logout()
  window.location.href = '/?logout=1'
}
</script>

<template>
  <div class="min-h-screen bg-slate-50 text-slate-900 antialiased">
    <main v-if="loading" class="min-h-screen flex items-center justify-center text-slate-500 text-sm">
      로딩 중...
    </main>

    <!-- 로그인 전 -->
    <main
      v-else-if="!user"
      class="min-h-screen flex items-center justify-center p-4"
    >
      <div class="w-full max-w-md bg-white rounded-2xl shadow-lg p-6 sm:p-8">
        <header class="mb-6">
          <div class="inline-flex items-center gap-2 mb-2">
            <span class="inline-block w-2 h-2 rounded-full bg-emerald-500" />
            <span class="text-xs font-medium text-emerald-700 uppercase tracking-wide">group-a</span>
          </div>
          <h1 class="text-2xl font-semibold">TaskBoard</h1>
          <p class="mt-1 text-sm text-slate-500">사내 칸반 · Node Express + Vue 3</p>
        </header>

        <div
          v-if="errorMsg"
          class="mb-4 rounded-lg bg-red-50 border border-red-200 px-3 py-2 text-sm text-red-700"
          role="alert"
        >
          오류: {{ errorMsg }}
        </div>

        <div class="bg-emerald-50 border border-emerald-200 rounded-lg p-4 mb-5 text-sm text-emerald-900">
          <p class="font-medium mb-1">silent SSO 시연</p>
          <p>이미 같은 그룹(group-a)의 Notebook 에 로그인되어 있다면 폼 없이 자동 로그인됩니다.</p>
        </div>

        <a
          href="/login"
          class="block w-full text-center rounded-lg bg-emerald-600 hover:bg-emerald-700 active:bg-emerald-800 text-white font-medium px-4 py-3 transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-emerald-500"
        >
          OAuth 로그인
        </a>
      </div>
    </main>

    <!-- 로그인 후 -->
    <div v-else class="min-h-screen flex flex-col">
      <!-- Header -->
      <header class="bg-white border-b border-slate-200 px-4 py-3 flex items-center gap-3">
        <span class="inline-flex items-center gap-2">
          <span class="w-2 h-2 rounded-full bg-emerald-500" />
          <span class="text-xs font-medium text-emerald-700 uppercase tracking-wide">group-a</span>
        </span>
        <h1 class="font-semibold">TaskBoard</h1>
        <div class="flex-1" />
        <div class="flex items-center gap-2">
          <div class="w-8 h-8 rounded-full bg-emerald-600 text-white flex items-center justify-center font-semibold uppercase text-sm">
            {{ displayName[0] }}
          </div>
          <span class="text-sm text-slate-700">{{ displayName }}</span>
          <button
            @click="logout"
            class="ml-2 text-sm text-slate-600 hover:text-slate-900 rounded border border-slate-300 px-3 py-1.5 hover:bg-slate-100"
          >
            로그아웃
          </button>
        </div>
      </header>

      <!-- Body: Sidebar + Board -->
      <div class="flex-1 flex overflow-hidden">
        <!-- Sidebar: boards -->
        <aside class="w-56 bg-white border-r border-slate-200 flex flex-col">
          <div class="px-3 py-2 flex items-center justify-between border-b border-slate-200">
            <span class="text-xs uppercase tracking-wide text-slate-500">Boards</span>
            <button @click="addBoard" class="text-emerald-600 hover:text-emerald-800 text-lg leading-none">+</button>
          </div>
          <ul class="flex-1 overflow-y-auto">
            <li v-if="boards.length === 0" class="px-3 py-4 text-sm text-slate-400">보드가 없습니다</li>
            <li
              v-for="b in boards"
              :key="b._id"
              :class="[
                'px-3 py-2 text-sm cursor-pointer group flex items-center justify-between',
                selectedBoardId === b._id ? 'bg-emerald-50 text-emerald-900' : 'hover:bg-slate-50',
              ]"
              @click="selectedBoardId = b._id"
            >
              <span class="truncate">{{ b.title }}</span>
              <span class="hidden group-hover:flex gap-1 text-xs text-slate-500">
                <button @click.stop="renameBoard(b)" class="hover:text-slate-900">✎</button>
                <button @click.stop="deleteBoard(b)" class="hover:text-red-600">✕</button>
              </span>
            </li>
          </ul>
        </aside>

        <!-- Board (3 columns) -->
        <section class="flex-1 overflow-x-auto p-4">
          <div v-if="!selectedBoardId" class="h-full flex items-center justify-center text-slate-400 text-sm">
            보드를 만들거나 선택하세요
          </div>
          <div v-else class="flex gap-4 h-full min-w-fit">
            <div
              v-for="col in COLUMNS"
              :key="col.id"
              class="w-72 flex-shrink-0 flex flex-col bg-white border border-slate-200 rounded-lg"
            >
              <header class="px-3 py-2 border-b border-slate-200 flex items-center justify-between">
                <span :class="['text-xs px-2 py-0.5 rounded-full font-medium', col.color]">
                  {{ col.label }}
                </span>
                <span class="text-xs text-slate-400">{{ columnTasks(col.id).length }}</span>
              </header>
              <div class="p-2 flex flex-col gap-2 flex-1 overflow-y-auto">
                <article
                  v-for="t in columnTasks(col.id)"
                  :key="t._id"
                  class="bg-slate-50 border border-slate-200 rounded-md px-3 py-2 group"
                >
                  <div class="text-sm">{{ t.title }}</div>
                  <div class="mt-1 flex items-center justify-between text-xs text-slate-400">
                    <span>{{ new Date(t.updatedAt).toLocaleDateString('ko-KR') }}</span>
                    <div class="hidden group-hover:flex gap-1">
                      <button
                        v-if="col.id !== 'todo'"
                        @click="moveTask(t, -1)"
                        class="hover:text-slate-900"
                        title="이전 컬럼"
                      >◀</button>
                      <button
                        v-if="col.id !== 'done'"
                        @click="moveTask(t, 1)"
                        class="hover:text-slate-900"
                        title="다음 컬럼"
                      >▶</button>
                      <button @click="deleteTask(t)" class="hover:text-red-600" title="삭제">✕</button>
                    </div>
                  </div>
                </article>
              </div>
              <footer class="p-2 border-t border-slate-200">
                <form @submit.prevent="addTask(col.id)" class="flex gap-2">
                  <input
                    v-model="newTaskInput[col.id]"
                    type="text"
                    placeholder="+ 새 작업"
                    class="flex-1 text-sm rounded border border-slate-300 px-2 py-1 focus:outline-none focus:ring-2 focus:ring-emerald-500"
                  />
                </form>
              </footer>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</template>

// examples/app3/frontend/app/page.tsx
'use client'

import { useEffect, useMemo, useState } from 'react'
import { api } from '@/lib/api'
import {
  TICKET_PRIORITIES,
  TICKET_STATUSES,
  type CurrentUser,
  type TicketDetail,
  type TicketPriority,
  type TicketStatus,
  type TicketSummary,
} from '@/lib/types'

export default function Page() {
  const [user, setUser] = useState<CurrentUser | null>(null)
  const [loading, setLoading] = useState(true)
  const [errorMsg, setErrorMsg] = useState<string | null>(null)

  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const e = params.get('error')
    const loggedOut = params.get('logout')
    if (e) {
      setErrorMsg(e)
      window.history.replaceState({}, '', '/')
    }
    if (loggedOut) {
      window.history.replaceState({}, '', '/')
      setLoading(false)
      return
    }
    api.me()
      .then(data => {
        if (data) {
          setUser(data)
          setLoading(false)
        } else if (e) {
          setLoading(false)
        } else {
          window.location.href = '/login'
        }
      })
      .catch(() => setLoading(false))
  }, [])

  const logout = async (): Promise<void> => {
    await api.logout()
    window.location.href = '/?logout=1'
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4">
        <p className="text-slate-500 text-sm">로딩 중...</p>
      </div>
    )
  }

  if (!user) return <LoginPage error={errorMsg} />
  return <HelpDeskApp user={user} onLogout={logout} />
}

// ─────────────────────────────────────────────
// 로그인 페이지
// ─────────────────────────────────────────────
function LoginPage({ error }: { error: string | null }) {
  return (
    <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4 antialiased text-slate-900">
      <main className="w-full max-w-md bg-white rounded-2xl shadow-lg p-6 sm:p-8">
        <header className="mb-6">
          <div className="inline-flex items-center gap-2 mb-2">
            <span className="inline-block w-2 h-2 rounded-full bg-amber-500" />
            <span className="text-xs font-medium text-amber-700 uppercase tracking-wide">group-b</span>
          </div>
          <h1 className="text-2xl font-semibold">HelpDesk</h1>
          <p className="mt-1 text-sm text-slate-500">외부 고객 지원 · FastAPI + Next.js</p>
        </header>

        {error && (
          <div className="mb-4 rounded-lg bg-red-50 border border-red-200 px-3 py-2 text-sm text-red-700" role="alert">
            오류: {error}
          </div>
        )}

        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-5 text-sm text-amber-900">
          <p className="font-medium mb-1">cross-group 차단 시연</p>
          <p>
            Notebook · TaskBoard (group-a) 에 이미 로그인되어 있어도, 이 앱은 다른 그룹(group-b) 이라{' '}
            <strong>로그인 폼이 다시 표시</strong>됩니다.
          </p>
        </div>

        <a
          href="/login"
          className="block w-full text-center rounded-lg bg-amber-600 hover:bg-amber-700 active:bg-amber-800 text-white font-medium px-4 py-3 transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-amber-500"
        >
          OAuth 로그인
        </a>
      </main>
    </div>
  )
}

// ─────────────────────────────────────────────
// 메인 앱
// ─────────────────────────────────────────────
const PRIORITY_COLOR: Record<TicketPriority, string> = {
  low:    'bg-slate-100 text-slate-700',
  normal: 'bg-blue-100 text-blue-700',
  high:   'bg-orange-100 text-orange-700',
  urgent: 'bg-red-100 text-red-700',
}

const STATUS_COLOR: Record<TicketStatus, string> = {
  open:     'bg-emerald-100 text-emerald-800',
  pending:  'bg-amber-100 text-amber-800',
  resolved: 'bg-slate-100 text-slate-700',
  closed:   'bg-slate-200 text-slate-500',
}

function HelpDeskApp({ user, onLogout }: { user: CurrentUser; onLogout: () => void }) {
  const [tickets, setTickets] = useState<TicketSummary[]>([])
  const [statusFilter, setStatusFilter] = useState<TicketStatus | ''>('')
  const [priorityFilter, setPriorityFilter] = useState<TicketPriority | ''>('')
  const [selectedId, setSelectedId] = useState<number | null>(null)
  const [detail, setDetail] = useState<TicketDetail | null>(null)
  const [showNewForm, setShowNewForm] = useState(false)

  const displayName = user.display_name ?? user.sub

  const refresh = async (): Promise<void> => {
    const list = await api.listTickets({
      status: statusFilter || undefined,
      priority: priorityFilter || undefined,
    })
    setTickets(list)
    if (selectedId && !list.find(t => t.id === selectedId)) setSelectedId(null)
  }

  useEffect(() => {
    void refresh()
  }, [statusFilter, priorityFilter])

  useEffect(() => {
    if (selectedId == null) {
      setDetail(null)
      return
    }
    void api.getTicket(selectedId).then(setDetail)
  }, [selectedId])

  const createTicket = async (
    subject: string,
    priority: TicketPriority,
    initialMessage: string,
  ): Promise<void> => {
    const created = await api.createTicket(subject, priority, initialMessage || undefined)
    setTickets(prev => [created, ...prev])
    setSelectedId(created.id)
    setShowNewForm(false)
  }

  const changeStatus = async (status: TicketStatus): Promise<void> => {
    if (!detail) return
    const updated = await api.updateTicket(detail.id, { status })
    setDetail({ ...detail, status: updated.status, updated_at: updated.updated_at })
    setTickets(prev => prev.map(t => (t.id === updated.id ? { ...t, status: updated.status } : t)))
  }

  const changePriority = async (priority: TicketPriority): Promise<void> => {
    if (!detail) return
    const updated = await api.updateTicket(detail.id, { priority })
    setDetail({ ...detail, priority: updated.priority, updated_at: updated.updated_at })
    setTickets(prev => prev.map(t => (t.id === updated.id ? { ...t, priority: updated.priority } : t)))
  }

  const addMessage = async (body: string): Promise<void> => {
    if (!detail) return
    const msg = await api.addMessage(detail.id, body)
    setDetail({ ...detail, messages: [...detail.messages, msg], updated_at: msg.created_at })
  }

  const deleteTicket = async (id: number): Promise<void> => {
    if (!window.confirm('티켓을 삭제할까요?')) return
    await api.deleteTicket(id)
    setTickets(prev => prev.filter(t => t.id !== id))
    if (selectedId === id) setSelectedId(null)
  }

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 antialiased flex flex-col">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 px-4 py-3 flex items-center gap-3">
        <span className="inline-flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-amber-500" />
          <span className="text-xs font-medium text-amber-700 uppercase tracking-wide">group-b</span>
        </span>
        <h1 className="font-semibold">HelpDesk</h1>
        <div className="flex-1" />
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-full bg-amber-600 text-white flex items-center justify-center font-semibold uppercase text-sm">
            {displayName[0]}
          </div>
          <span className="text-sm text-slate-700">{displayName}</span>
          <button
            onClick={onLogout}
            className="ml-2 text-sm text-slate-600 hover:text-slate-900 rounded border border-slate-300 px-3 py-1.5 hover:bg-slate-100"
          >
            로그아웃
          </button>
        </div>
      </header>

      {/* Body */}
      <div className="flex-1 flex overflow-hidden">
        {/* Ticket list + filters */}
        <section className="w-96 bg-white border-r border-slate-200 flex flex-col">
          <div className="px-3 py-2 border-b border-slate-200 flex items-center gap-2">
            <select
              value={statusFilter}
              onChange={e => setStatusFilter(e.target.value as TicketStatus | '')}
              className="text-xs rounded border border-slate-300 px-2 py-1"
            >
              <option value="">모든 상태</option>
              {TICKET_STATUSES.map(s => <option key={s} value={s}>{s}</option>)}
            </select>
            <select
              value={priorityFilter}
              onChange={e => setPriorityFilter(e.target.value as TicketPriority | '')}
              className="text-xs rounded border border-slate-300 px-2 py-1"
            >
              <option value="">모든 우선순위</option>
              {TICKET_PRIORITIES.map(p => <option key={p} value={p}>{p}</option>)}
            </select>
            <button
              onClick={() => setShowNewForm(true)}
              className="ml-auto text-xs rounded bg-amber-600 hover:bg-amber-700 text-white px-3 py-1"
            >
              + 새 티켓
            </button>
          </div>
          <ul className="flex-1 overflow-y-auto">
            {tickets.length === 0 && (
              <li className="px-4 py-6 text-sm text-slate-400">티켓이 없습니다</li>
            )}
            {tickets.map(t => (
              <li
                key={t.id}
                className={`px-4 py-3 cursor-pointer border-b border-slate-100 group ${
                  selectedId === t.id ? 'bg-amber-50' : 'hover:bg-slate-50'
                }`}
                onClick={() => setSelectedId(t.id)}
              >
                <div className="flex items-center gap-2 mb-1">
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${STATUS_COLOR[t.status]}`}>
                    {t.status}
                  </span>
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${PRIORITY_COLOR[t.priority]}`}>
                    {t.priority}
                  </span>
                  <span className="ml-auto text-xs text-slate-400">#{t.id}</span>
                </div>
                <div className="text-sm font-medium truncate">{t.subject}</div>
                <div className="text-xs text-slate-500 mt-1 flex items-center justify-between">
                  <span>{t.message_count} 메시지</span>
                  <span>{new Date(t.updated_at).toLocaleString('ko-KR')}</span>
                </div>
              </li>
            ))}
          </ul>
        </section>

        {/* Detail */}
        <section className="flex-1 flex flex-col overflow-hidden">
          {showNewForm ? (
            <NewTicketForm onCancel={() => setShowNewForm(false)} onCreate={createTicket} />
          ) : detail ? (
            <TicketDetailPane
              detail={detail}
              currentSub={user.sub}
              onChangeStatus={changeStatus}
              onChangePriority={changePriority}
              onAddMessage={addMessage}
              onDelete={() => deleteTicket(detail.id)}
            />
          ) : (
            <div className="flex-1 flex items-center justify-center text-slate-400 text-sm">
              왼쪽에서 티켓을 선택하거나 새로 만드세요
            </div>
          )}
        </section>
      </div>
    </div>
  )
}

// ─────────────────────────────────────────────
// 새 티켓 폼
// ─────────────────────────────────────────────
function NewTicketForm({
  onCreate,
  onCancel,
}: {
  onCreate: (subject: string, priority: TicketPriority, message: string) => Promise<void>
  onCancel: () => void
}) {
  const [subject, setSubject] = useState('')
  const [priority, setPriority] = useState<TicketPriority>('normal')
  const [message, setMessage] = useState('')

  return (
    <div className="p-8 max-w-2xl">
      <h2 className="text-xl font-semibold mb-4">새 티켓</h2>
      <form
        onSubmit={async e => {
          e.preventDefault()
          if (!subject.trim()) return
          await onCreate(subject.trim(), priority, message.trim())
        }}
        className="space-y-4"
      >
        <div>
          <label className="block text-sm font-medium mb-1">제목</label>
          <input
            value={subject}
            onChange={e => setSubject(e.target.value)}
            required
            className="w-full rounded border border-slate-300 px-3 py-2 focus:outline-none focus:ring-2 focus:ring-amber-500"
            placeholder="어떤 도움이 필요하신가요?"
          />
        </div>
        <div>
          <label className="block text-sm font-medium mb-1">우선순위</label>
          <select
            value={priority}
            onChange={e => setPriority(e.target.value as TicketPriority)}
            className="rounded border border-slate-300 px-3 py-2"
          >
            {TICKET_PRIORITIES.map(p => <option key={p} value={p}>{p}</option>)}
          </select>
        </div>
        <div>
          <label className="block text-sm font-medium mb-1">메시지 (선택)</label>
          <textarea
            value={message}
            onChange={e => setMessage(e.target.value)}
            rows={6}
            className="w-full rounded border border-slate-300 px-3 py-2 focus:outline-none focus:ring-2 focus:ring-amber-500"
            placeholder="자세한 설명을 적어주세요"
          />
        </div>
        <div className="flex gap-2">
          <button
            type="submit"
            className="rounded bg-amber-600 hover:bg-amber-700 text-white px-4 py-2 text-sm font-medium"
          >
            생성
          </button>
          <button
            type="button"
            onClick={onCancel}
            className="rounded border border-slate-300 hover:bg-slate-100 text-slate-700 px-4 py-2 text-sm"
          >
            취소
          </button>
        </div>
      </form>
    </div>
  )
}

// ─────────────────────────────────────────────
// 티켓 상세
// ─────────────────────────────────────────────
function TicketDetailPane({
  detail,
  currentSub,
  onChangeStatus,
  onChangePriority,
  onAddMessage,
  onDelete,
}: {
  detail: TicketDetail
  currentSub: string
  onChangeStatus: (s: TicketStatus) => Promise<void>
  onChangePriority: (p: TicketPriority) => Promise<void>
  onAddMessage: (body: string) => Promise<void>
  onDelete: () => Promise<void>
}) {
  const [draft, setDraft] = useState('')

  const ordered = useMemo(
    () => [...detail.messages].sort((a, b) => a.created_at.localeCompare(b.created_at)),
    [detail.messages],
  )

  return (
    <div className="flex-1 flex flex-col overflow-hidden">
      <header className="px-6 py-4 border-b border-slate-200 bg-white">
        <div className="flex items-center gap-2 mb-2">
          <span className="text-xs text-slate-400">#{detail.id}</span>
          <select
            value={detail.status}
            onChange={e => onChangeStatus(e.target.value as TicketStatus)}
            className={`text-xs px-2 py-1 rounded-full font-medium ${STATUS_COLOR[detail.status]}`}
          >
            {TICKET_STATUSES.map(s => <option key={s} value={s}>{s}</option>)}
          </select>
          <select
            value={detail.priority}
            onChange={e => onChangePriority(e.target.value as TicketPriority)}
            className={`text-xs px-2 py-1 rounded-full font-medium ${PRIORITY_COLOR[detail.priority]}`}
          >
            {TICKET_PRIORITIES.map(p => <option key={p} value={p}>{p}</option>)}
          </select>
          <div className="flex-1" />
          <button
            onClick={onDelete}
            className="text-xs text-slate-500 hover:text-red-600 rounded border border-slate-300 hover:border-red-300 px-2 py-1"
          >
            삭제
          </button>
        </div>
        <h2 className="text-xl font-semibold">{detail.subject}</h2>
        <p className="text-xs text-slate-400 mt-1">
          생성 {new Date(detail.created_at).toLocaleString('ko-KR')} · 갱신{' '}
          {new Date(detail.updated_at).toLocaleString('ko-KR')}
        </p>
      </header>

      <div className="flex-1 overflow-y-auto px-6 py-4 space-y-3">
        {ordered.length === 0 && (
          <p className="text-sm text-slate-400">아직 메시지가 없습니다</p>
        )}
        {ordered.map(m => {
          const mine = m.author_sub === currentSub
          return (
            <div key={m.id} className={`flex ${mine ? 'justify-end' : 'justify-start'}`}>
              <div
                className={`max-w-2xl rounded-2xl px-4 py-2 ${
                  mine ? 'bg-amber-100 text-amber-900' : 'bg-white border border-slate-200'
                }`}
              >
                <div className="text-xs text-slate-500 mb-1">
                  {m.author_sub} · {new Date(m.created_at).toLocaleString('ko-KR')}
                </div>
                <div className="text-sm whitespace-pre-wrap">{m.body}</div>
              </div>
            </div>
          )
        })}
      </div>

      <form
        onSubmit={async e => {
          e.preventDefault()
          if (!draft.trim()) return
          await onAddMessage(draft.trim())
          setDraft('')
        }}
        className="border-t border-slate-200 bg-white px-4 py-3 flex gap-2"
      >
        <input
          value={draft}
          onChange={e => setDraft(e.target.value)}
          placeholder="메시지 추가..."
          className="flex-1 rounded border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-amber-500"
        />
        <button
          type="submit"
          className="rounded bg-amber-600 hover:bg-amber-700 text-white px-4 py-2 text-sm font-medium"
        >
          보내기
        </button>
      </form>
    </div>
  )
}
